services:
  - type: web
    name: govi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn agent:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: govi-frontend
    env: node
    buildCommand: pnpm install -D tailwindcss@latest postcss@latest autoprefixer@latest && pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_URL
        value: https://govi.onrender.com
      - key: NEXT_PUBLIC_WEBSOCKET_URL
        value: wss://govi.onrender.com