services: 
  - type: web
    name: govi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python agent.py
    envVars:
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000