[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile && pnpm run build"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"