services:
  - type: web
    name: govi-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://govi.onrender.com
      - key: NEXT_PUBLIC_CONN_DETAILS_ENDPOINT
        value: https://govi.onrender.com/api/connection-details
      - key: NEXT_PUBLIC_WEBSOCKET_URL
        value: wss://govi.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true